    document.body.onload=animate;
    function animate(){
       document.getElementById("pic").style.height="70%";
       document.getElementById("pic").style.margin="5% 5% 5% 5%";
    };
    let count=0;
     document.getElementById("firstbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
            document.getElementById("firstdiv").style.display="inline-block";
         }
         else{
            document.getElementById("firstdiv").style.display="none";   
         }
     });
     document.getElementById("secondbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("seconddiv").style.display="inline-block";
         }
         else{
            document.getElementById("seconddiv").style.display="none";   
         }
     });
     document.getElementById("thirdbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("thirddiv").style.display="inline-block";
         }
         else{
            document.getElementById("thirddiv").style.display="none";   
         }
     });
     document.getElementById("fourthbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("fourthdiv").style.display="inline-block";
         }
         else{
            document.getElementById("fourthdiv").style.display="none";   
         }
     });
     document.getElementById("fifthbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("fifthdiv").style.display="inline-block";
         }
         else{
            document.getElementById("fifthdiv").style.display="none";   
         }
     });
     document.getElementById("sixthbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("sixthdiv").style.display="inline-block";
         }
         else{
            document.getElementById("sixthdiv").style.display="none";   
         }
     });
     document.getElementById("seventhbtn").addEventListener("click",function(){
         count++;
         if(count%2!=0){
         document.getElementById("seventhdiv").style.display="inline-block";
         }
         else{
            document.getElementById("seventhdiv").style.display="none";   
         }
     });
